[[manager.prepend_keymap]]
on   = [ "g", "a" ]
run  = "cd /archive"
desc = "Cd to /archive"

[[manager.prepend_keymap]]
on   = [ "g", "f" ]
run  = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[manager.prepend_keymap]]
on   = [ "g", "l" ]
run  = "cd ~/gitlib"
desc = "Cd to ~/gitlib"
