[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "size"
show_hidden = false
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll", "touch", "move", "drag"]

[preview]
tab_size = 2
max_width = 600
max_height = 900
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[open]
rules = [
  { mime = "text/*", use = ["edit"] },
  { mime = "image/*", use = ["open", "edit_image"] },
  { mime = "video/*", use = ["play"] },
  { mime = "application/*", use = ["open"] },

  { name = "*.py", use = ["edit", "execute"] },
  # { name = "*.sql", use = ["edit", "execute"] },
  { mime = "text/csv", use = ["open", "edit"] },
  { mime = "*.json", use = ["edit", "open_in_browser"] },
  { mime = "text/html", use = ["edit", "open_in_browser"] },
  { mime = "application/zip", use = ["open_archive", "extract_here", "extract_to_named"] },
  { mime = "application/json", use = ["open", "edit", "open_in_browser"] },
  { mime = "application/pdf", use = ["open", "open_in_browser"] },
  { mime = "inode/directory", use = ["open_terminal"] },

  { name = "*", use = ["reveal"] },
]

[[opener.open]]
run = 'xdg-open "$@"'
desc = "Open"

[[opener.edit]]
run = 'lvim "$@"'
desc = "Edit with Vim"
block = true

[[opener.execute]]
run = 'python3 "$@"'
desc = "Execute (code)"

[[opener.open_in_browser]]
run = 'google-chrome-stable "$@"'
desc = "Open in Chrome"
orphan = true

[[opener.edit_image]]
run = 'display-im6 "$@"'
desc = "Edit with Imagemagick"
orphan = true

[[opener.play]]
run = 'vlc "$@"'
desc = "Play with VLC"
orphan = true

[[opener.extract_here]]
run = 'unzip "$1"'
desc = "Extract Here"

[[opener.extract_to_named]]
run = '''
dir="${1%.*}"
mkdir -p "$dir"
unzip -d "$dir" "$1"
'''
desc = "Extract with folder/"

[[opener.open_archive]]
run = 'file-roller "$@"'
orphan = true
desc = "Open with Archive Manager"

[[opener.open_terminal]]
run = 'kitty --working-directory "$1"'
desc = "Open in Terminal"

[[opener.reveal]]
run = 'nautilus --select "$1"'
desc = "Reveal in Files"
