[manager]
layout         = [ 1, 4, 3 ]
sort_by        = "modified"
sort_sensitive = true
sort_reverse   = true
sort_dir_first = true
linemode       = "none"
show_hidden    = false
show_symlink   = true

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
	{ exec = '$EDITOR "$@"', block = true,  desc = "Vim", for = "unix" },
	{ exec = 'code "%*"',    orphan = true, desc = "Vim", for = "windows" },
]
open = [
	{ exec = 'xdg-open "$@"',             desc = "Open", for = "linux" },
	{ exec = 'open "$@"',                 desc = "Open", for = "macos" },
	{ exec = 'start "%1"', orphan = true, desc = "Open", for = "windows" }
]
reveal = [
	{ exec = 'open -R "$1"',                       desc = "Reveal", for = "macos" },
	{ exec = 'explorer /select,%1', orphan = true, desc = "Reveal", for = "windows" },
	{ exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
	{ exec = 'unzip "$1"', desc = "Extract here", for = "unix" },
	{ exec = 'unzip "%1"', desc = "Extract here", for = "windows" },
]
play = [
	{ exec = 'vlc "$@"', orphan = true, for = "unix" },
	{ exec = 'vlc "%1"', orphan = true, for = "windows" },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]

switch = [
	{ exec = 'echo $@>$YAZI_UPDATE_DIRECTORY && pkill yazi', desc="Switch Directory", orphan = true, for = "unix" },
]

archive = [
	{ exec = 'zip -r "$1.zip" $(basename $1)', desc="Archive", orphan = true, for = "unix" },
]


[open]
rules = [
	{ name = "*/", use = [ "switch", "open", "reveal", "archive" ] },

	{ mime = "text/*",  use = [ "edit", "open", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal" ] },
	{ mime = "video/*", use = [ "play", "reveal" ] },
	{ mime = "audio/*", use = [ "play", "reveal" ] },
	{ mime = "inode/x-empty", use = [ "edit", "reveal" ] },

	{ mime = "application/json", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },

	{ mime = "application/zip",             use = [ "open", "extract", "reveal" ] },
	{ mime = "application/gzip",            use = [ "open", "extract", "reveal" ] },
	{ mime = "application/x-tar",           use = [ "open", "extract", "reveal" ] },
	{ mime = "application/x-bzip",          use = [ "open", "extract", "reveal" ] },
	{ mime = "application/x-bzip2",         use = [ "open", "extract", "reveal" ] },
	{ mime = "application/x-7z-compressed", use = [ "open", "extract", "reveal" ] },
	{ mime = "application/x-rar",           use = [ "open", "extract", "reveal" ] },

	{ mime = "*", use = [ "open", "reveal" ] },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[plugins]
preload = []

[log]
enabled = false
